spring.application.name=MedSchedule

# Banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/medschedule
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Login temporario do Spring Security (fase de Seguranca ainda nao foi construida)
spring.security.user.name=idd_jmendes
spring.security.user.password={bcrypt}$2a$10$XquYsV0ZwbZlxgmvRjFiIuZ.Zhz8VUbRJUKJ1DZg8kBtQgiJVkZiy
