spring.application.name=MedSchedule

# Banco H2 em memoria
spring.datasource.url=jdbc:h2:mem:medschedule
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Login temporario do Spring Security (fase de Seguranca ainda nao foi construida)
spring.security.user.name=idd_jmendes
spring.security.user.password={bcrypt}$2a$10$XquYsV0ZwbZlxgmvRjFiIuZ.Zhz8VUbRJUKJ1DZg8kBtQgiJVkZiy
